name: 🌋2. Acceso a la fortaleza Prohibida

on: 
  workflow_dispatch:

jobs:
    acceso-a-la-base:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        # Node 24 por defecto (Node 20 deprecated) - GitHub usará la última versión estable
        steps:
            - name: El agente se llega a la fortaleza
              shell: bash
              run: |
                echo "Agente ${{ github.actor }} llega a la fortaleza"
                echo ""
                echo "Buscar los archivos de la legión"
                ls -al
                echo ""
                echo "❌ pero qué paso? no hay nada"

            - name: Brainiac desbloquea la bóbeda
              uses: actions/checkout@v4 # Da acceso a los archivos del repositorio
            
            - name: Ahora si, vamos a ver los planes
              run: |
                echo "Buscar los archivos de la legión"
                ls -al
                echo ""
                echo "✅ Funciona"
                echo ""
                echo "Planes:"
                ls -al planes/
                echo ""
                echo "Villanos:"
                ls -al miembros/
                echo ""
                echo "Inteligencia:"
                ls -al inteligencia/

