name: 3. Comunicador de la legión

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      villano:
        description: "Qué villano envía el mensaje?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto
          - Joker
          - Mystique
          - Brainiac
      mensaje:
        description: 'Mensaje para el consejo'
        required: true
        default: 'La misión fue un éxito 🚀'
      prioridad:
        description: "Nivel de prioridad"
        required: true
        type: choice
        options:
          - 🟢 Normal
          - 🌕 Alta
          - 🔴 Crítica        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  transmitir-mensaje:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Instalar el transmisor de mensajes
        run: |
          echo "Instalando el transmisor de mensajes"
          echo "=============================="
          sudo apt-get install -y cowsay

      - name: Transmitiendo mensaje de los inputs del workflow
        run: |
          echo "Transmisión de mensaje interceptado"
          echo "=============================="
          echo ""
          echo "De: ${{ inputs.villano }}"
          echo ""
          echo "Fecha: $(date -u +"%d-%m-%Y_%H:%M:%S UTC")"
          echo "Mensaje:"
          cowsay -f eyes "${{ inputs.mensaje }}"
          echo ""
          echo "Prioridad: ${{ inputs.prioridad }}"



